### PR TITLE
add loading indicator to the cart page

### PR DESCRIPTION
**Pull request by yacineahmaich**
### Description

This pull request solves #78

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

Before submitting this pull request, please make sure to review and check the following:

- [x] The code follows the project's coding guidelines and style.
- [] Tests have been added or updated to cover the changes (if applicable).
- [ ] All new and existing tests pass successfully.
- [ ] The documentation has been updated to reflect the changes (if applicable).
- [x] The branch is up-to-date with the latest changes from the target branch.

### Related Issues

- Fixes #<issue_number>
- Related to #<78>

### Additional Notes (Optional)

Add any additional information or context that may be helpful for reviewers.

### CODE REVIEW

**Comment by KikinovK** [comment]
Thanks for refactoring the catalog page, but the (issue<78>)[https://github.com/yevheniiorhanistyi/eCommerce-Application/issues/78] specified the cart page

**Comment by KikinovK** [comment]
Could you make a pull request to `develop` and `main`

**Comment by yacineahmaich** [comment]
> Thanks for refactoring the catalog page, but the issue<78> specified the cart page

I just take the already exiting spinner and abstract it into a reusable component and use it in both Catalog and Cart page.
The cart page also was implemented!

**Comment by KikinovK** [comment]
sorry

**Review by yevheniiorhanistyi — APPROVED** [review]

**Pull request closed without merging**
